### ISSUE TITLE
Bug: Shadows around borders keep darkening on clicking

### ISSUE THREAD

**Issue by chiamyunqing** [AY2021S1-CS2103T-W12-1/tp#117]
For patient details UI (but it's cool). (Change getroot.setchild or sth kiv)

**Comment by LeeMingDe** [comment]
You can take a look at the `RoomListPanel.java` for references. I suspect the problem arose because you are calling `patientDetailsPanel = new PatientDetailsPanel(patientToDisplay)` and `patientDetailsPanelPlaceholder.getChildren().add(patientDetailsPanel.getRoot())` repeatedly. Perhaps you can move both these LOC from the `handleMouseClick` and `updateDetailsIfChanged` method into the constructor for `PatientListPanel.java`

**Comment by chiamyunqing** [comment]
Bro that was spot on. Error was in the handleMouseClick
